name: "Python Code Style, Quality, and Lint"
description: "Supports a plethora of tools for checking your Python code and packages"
branding:
  icon: "terminal"
  color: "white"
inputs:
  python-root-list:
    description: "A list of all paths to test"
    required: false
    default: "."
  virtual-env:
    description: "The name of the virtual environment to use for running the tools"
    required: false
    default: "python-lint-plus"
  use-black:
    description: "Use Black"
    required: false
    default: false
  black-version:
    description: "The version of black to use"
    required: false
    default: ""
  use-yapf:
    description: "Use yapf"
    required: false
    default: false
  yapf-version:
    description: "The version of yapf to use"
    required: false
    default: ""
  use-isort:
    description: "Use isort"
    required: false
    default: false
  isort-version:
    description: "The version of isort to use"
    required: false
    default: ""
  use-docformatter:
    description: "Use docformatter"
    required: false
    default: false
  docformatter-version:
    description: "The version of docformatter to use"
    required: false
    default: ""
  use-pycodestyle:
    description: "Use pycodestyle"
    required: false
    default: false
  pycodestyle-version:
    description: "The version of pycodestyle to use"
    required: false
    default: ""
  use-autopep8:
    description: "Use autopep8"
    required: false
    default: false
  autopep8-version:
    description: "The version of autope8 to use"
    required: false
    default: ""
  use-pydocstyle:
    description: "Use pydocstyle"
    required: false
    default: false
  pydocstyle-version:
    description: "The version of pydocstyle to use"
    required: false
    default: ""
  use-mypy:
    description: "Use mypy"
    required: false
    default: false
  mypy-version:
    description: "The version of mypy to use"
    required: false
    default: ""
  use-pylint:
    description: "Use Pylint"
    required: false
    default: false
  pylint-version:
    description: "The version of pylint to use"
    required: false
    default: ""
  use-flake8:
    description: "Use Flake8"
    required: false
    default: false
  flake8-version:
    description: "The version of flake8 to use"
    required: false
    default: ""
  use-mccabe:
    description: "Use mccabe"
    required: false
    default: false
  mccabe-version:
    description: "The version of mccabe to use"
    required: false
    default: ""
  use-radon:
    description: "Use radon"
    required: false
    default: false
  radon-version:
    description: "The version of radon to use"
    required: false
    default: ""
  use-rstcheck:
    description: "Use rstcheck"
    required: false
    default: false
  rstcheck-version:
    description: "The version of rstcheck to use"
    required: false
    default: ""
  use-check-manifest:
    description: "Use check-manifest"
    required: false
    default: false
  check-manifest-version:
    description: "The version of check-manifest to use"
    required: false
    default: ""
  use-pyroma:
    description: "Use pyroma"
    required: false
    default: false
  pyroma-version:
    description: "The version of pyroma to use"
    required: false
    default: ""
  extra-black-options:
    description: "Extra options: black --check $(extra-black-options) $(python-root-list)"
    required: false
    default: ""
  extra-yapf-options:
    description: "Extra options: yapf $(extra-yapf-options) $(python-root-list)"
    required: false
    default: ""
  extra-isort-options:
    description: "Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff "
    required: false
    default: ""
  extra-docformatter-options:
    description: "Extra options: docformatter $(extra-docformatter-options) $(python-root-list)"
    required: false
    default: ""
  extra-pycodestyle-options:
    description: "Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)"
    required: false
    default: ""
  extra-autopep8-options:
    description: "Extra options: autopep8 $(extra-autopep8-options) $(python-root-list)"
    required: false
    default: ""
  extra-pydocstyle-options:
    description: "Extra options: pydocstyle $(extra-pydocstyle-options) $(python-root-list)"
    required: false
    default: ""
  extra-mypy-options:
    description: "Extra options: mypy $(extra-mypy-options) $(python-root-list)"
    required: false
    default: ""
  extra-pylint-options:
    description: "Extra options: pylint $(extra-pylint-options) $(python-root-list)"
    required: false
    default: ""
  extra-flake8-options:
    description: "Extra options: flake8 $(extra-flake8-options) $(python-root-list)"
    required: false
    default: ""
  extra-mccabe-options:
    description: "Extra options: python -m mccabe $(extra-mccabe-options) $(python-root-list)"
    required: false
    default: ""
  extra-radon-options:
    description: "Extra options: radon $(extra-radon-options) $(python-root-list)"
    required: false
    default: ""
  extra-rstcheck-options:
    description: "Extra options: rstcheck $(extra-rstcheck-options) $(python-root-list)"
    required: false
    default: ""
  extra-manifest-options:
    description: "Extra options: check-manifest $(extra-manifest-options) ."
    required: false
    default: ""
  extra-pyroma-options:
    description: "Extra options: pyroma $(extra-manifest-options) ."
    required: false
    default: ""
  python-version:
    description: "Python version to use for the run.  Defaults to 3.10."
    required: false
    default: '3.10'
  architecture:
    description: "The architecture (x86 or x64) to use for the run.  Defaults to x64."
    required: false
    default: 'x64'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        architecture: ${{ inputs.architecture }}

    - name: Linux Lint
      if: ${{ runner.os == 'Linux' }}
      run: >
        ${{ github.action_path }}/entrypoint.sh
        '${{ inputs.python-root-list }}'
        '${{ inputs.virtual-env }}'
        ${{ inputs.use-black }}
        '${{ inputs.black-version }}'
        ${{ inputs.use-yapf }}
        '${{ inputs.yapf-version }}'
        ${{ inputs.use-isort }}
        '${{ inputs.isort-version }}'
        ${{ inputs.use-docformatter }}
        '${{ inputs.docformatter-version }}'
        ${{ inputs.use-pycodestyle }}
        '${{ inputs.pycodestyle-version }}'
        ${{ inputs.use-autopep8 }}
        '${{ inputs.autopep8-version }}'
        ${{ inputs.use-pydocstyle }}
        '${{ inputs.pydocstyle-version }}'
        ${{ inputs.use-mypy }}
        '${{ inputs.mypy-version }}'
        ${{ inputs.use-pylint }}
        '${{ inputs.pylint-version }}'
        ${{ inputs.use-flake8 }}
        '${{ inputs.flake8-version }}'
        ${{ inputs.use-mccabe }}
        '${{ inputs.mccabe-version }}'
        ${{ inputs.use-radon }}
        '${{ inputs.radon-version }}'
        ${{ inputs.use-rstcheck }}
        '${{ inputs.rstcheck-version }}'
        ${{ inputs.use-check-manifest }}
        '${{ inputs.check-manifest-version }}'
        ${{ inputs.use-pyroma }}
        '${{ inputs.pyroma-version }}'
        '${{ inputs.extra-black-options }}'
        '${{ inputs.extra-yapf-options }}'
        '${{ inputs.extra-isort-options }}'
        '${{ inputs.extra-docformatter-options }}'
        '${{ inputs.extra-pycodestyle-options }}'
        '${{ inputs.extra-autopep8-options }}'
        '${{ inputs.extra-pydocstyle-options }}'
        '${{ inputs.extra-mypy-options }}'
        '${{ inputs.extra-pylint-options }}'
        '${{ inputs.extra-flake8-options }}'
        '${{ inputs.extra-mccabe-options }}'
        '${{ inputs.extra-radon-options }}'
        '${{ inputs.extra-rstcheck-options }}'
        '${{ inputs.extra-manifest-options }}'
        '${{ inputs.extra-pyroma-options }}'
      shell: bash

